"""empty message

Revision ID: 0381ed60831c
Revises: f31caab29a7d
Create Date: 2023-01-24 15:02:28.161356

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0381ed60831c'
down_revision = 'f31caab29a7d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('contact', 'birthday',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.String(length=50),
               existing_nullable=True)
    op.alter_column('contact', 'number',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=20),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('contact', 'number',
               existing_type=sa.String(length=20),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('contact', 'birthday',
               existing_type=sa.String(length=50),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    # ### end Alembic commands ###
