"""add Contact model

Revision ID: f31caab29a7d
Revises: 
Create Date: 2023-01-23 19:21:29.850763

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f31caab29a7d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contact',
    sa.Column('contact_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('first_name', sa.String(length=50), nullable=True),
    sa.Column('last_name', sa.String(length=50), nullable=True),
    sa.Column('number', sa.Integer(), nullable=True),
    sa.Column('email', sa.String(length=50), nullable=True),
    sa.Column('address', sa.String(length=250), nullable=True),
    sa.Column('birthday', sa.DateTime(), nullable=True),
    sa.Column('relationship', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.Column('tags', sa.ARRAY(sa.String()), nullable=True),
    sa.PrimaryKeyConstraint('contact_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('contact')
    # ### end Alembic commands ###
